/**
 * Generates firmware/include/zone_secrets.h — the gitignored header holding the
 * ESP32 node's zone identity.
 *
 * The node addresses the backend by zone UUID and authenticates with the zone's
 * plaintext API key. The UUID lives in Postgres, the key only in the gitignored
 * file the seed writes, and both change on every `pnpm db:seed` — so copying
 * them by hand between two places is the step people get wrong.
 *
 *   pnpm firmware:config                      # print the block (iot-lab)
 *   pnpm firmware:config -- --write           # write zone_secrets.h
 *   pnpm firmware:config -- server-room --write
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import { PrismaClient } from "@prisma/client"

const BACKEND_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  ".."
)
const FIRMWARE_ROOT = path.resolve(BACKEND_ROOT, "..", "firmware")
const SECRETS_HEADER = path.join(FIRMWARE_ROOT, "include", "zone_secrets.h")
const zoneDiagram = (code: string) =>
  path.join(FIRMWARE_ROOT, "zones", code, "diagram.json")

const DEFAULT_ZONE = "iot-lab"

// `pnpm firmware:config -- server-room` forwards a literal "--" argument.
const rawArgs = process.argv.slice(2).filter((arg) => arg !== "--")
const shouldWrite = rawArgs.includes("--write")
const allZones = rawArgs.includes("--all")
const registryMode = rawArgs.includes("--registry")

function requestedZoneCode(): string {
  return rawArgs.find((arg) => !arg.startsWith("--")) ?? DEFAULT_ZONE
}

/**
 * Write every zone's header at once, into include/zones/<code>.h.
 *
 * Each PlatformIO environment compiles against one of these, so all three nodes
 * can be built and simulated at the same time rather than one at a time. The
 * single-zone flow still writes include/zone_secrets.h for a plain `pio run`.
 */
async function writeAllZones(
  prisma: PrismaClient,
  keys: Record<string, string>
): Promise<void> {
  const zonesDir = path.join(FIRMWARE_ROOT, "include", "zones")
  mkdirSync(zonesDir, { recursive: true })

  const zones = await prisma.zone.findMany({
    where: { isActive: true },
    include: { sensors: true },
    orderBy: { code: "asc" },
  })

  let written = 0
  for (const zone of zones) {
    const apiKey = keys[zone.code]
    if (!apiKey) {
      console.log(`  skip ${zone.code} — no key in .dev-zone-keys.json`)
      continue
    }
    const has = (type: string) => zone.sensors.some((s) => s.type === type)
    const flags: Array<[string, boolean]> = [
      ["REPORT_FIRE", has("FLAME")],
      ["REPORT_GAS", has("GAS")],
      ["REPORT_WATER", has("WATER")],
      ["REPORT_OCCUPANCY", has("OCCUPANCY")],
    ]

    writeFileSync(
      path.join(zonesDir, `${zone.code}.h`),
      [
        "#pragma once",
        "",
        "// GENERATED by `pnpm firmware:config -- --all` — do not commit.",
        `// Zone: ${zone.name}`,
        "namespace AppConfig {",
        "",
        `static constexpr char ZONE_CODE[] = "${zone.code}";`,
        `static constexpr char ZONE_UUID[] = "${zone.id}";`,
        `static constexpr char ZONE_API_KEY[] = "${apiKey}";`,
        "",
        ...flags.map(
          ([n, on]) =>
            `static constexpr bool ${n.padEnd(18)} = ${on ? "true" : "false"};`
        ),
        "",
        "}  // namespace AppConfig",
        "",
      ].join("\n"),
      "utf8"
    )
    written++
    console.log(
      `  include/zones/${zone.code}.h  ${flags
        .filter(([, on]) => on)
        .map(([n]) => n.replace("REPORT_", "").toLowerCase())
        .join(", ")}`
    )
  }

  console.log(`\n  ${written} zone header(s) written. Build them all with:`)
  console.log("    cd firmware && pio run\n")
}

/**
 * Write every zone into one header as a runtime table.
 *
 * Wokwi simulates a single microcontroller per project, so three nodes cannot
 * share one diagram — only one board would ever be flashed. Compiling all the
 * zones into one binary and letting a button select between them gives the same
 * demo from a single board: press it and the node becomes a different room,
 * with that room's credentials and that room's sensor set.
 */
async function writeRegistry(
  prisma: PrismaClient,
  keys: Record<string, string>
): Promise<void> {
  const zones = (
    await prisma.zone.findMany({
      where: { isActive: true },
      include: { sensors: true },
      orderBy: { code: "asc" },
    })
  ).filter((zone) => keys[zone.code])

  const rows = zones.map((zone) => {
    const has = (type: string) => zone.sensors.some((s) => s.type === type)
    return (
      `    { "${zone.code}", "${zone.id}",\n` +
      `      "${keys[zone.code]}",\n` +
      `      ${has("FLAME")}, ${has("GAS")}, ${has("WATER")}, ${has("OCCUPANCY")} },`
    )
  })

  writeFileSync(
    path.join(FIRMWARE_ROOT, "include", "zone_registry.h"),
    [
      "#pragma once",
      "",
      "// GENERATED by `pnpm firmware:config -- --registry` — do not commit.",
      "// Holds live zone API keys.",
      "",
      "namespace AppConfig {",
      "",
      "struct ZoneConfig {",
      "  const char* code;",
      "  const char* uuid;",
      "  const char* apiKey;",
      "  bool reportFire;",
      "  bool reportGas;",
      "  bool reportWater;",
      "  bool reportOccupancy;",
      "};",
      "",
      "static constexpr ZoneConfig ZONE_REGISTRY[] = {",
      ...rows,
      "};",
      "",
      `static constexpr uint8_t ZONE_COUNT = ${zones.length};`,
      "",
      "}  // namespace AppConfig",
      "",
    ].join("\n"),
    "utf8"
  )

  for (const zone of zones) {
    const has = (t: string) => zone.sensors.some((s) => s.type === t)
    console.log(
      `  ${zone.code.padEnd(14)} ${["FLAME", "GAS", "WATER", "OCCUPANCY"]
        .filter(has)
        .join(", ")
        .toLowerCase()}`
    )
  }
  console.log(
    `\n  include/zone_registry.h — ${zones.length} zones, switchable at runtime.\n`
  )
}

async function main(): Promise<void> {
  const zoneCode = requestedZoneCode()
  const keyFile = path.join(BACKEND_ROOT, ".dev-zone-keys.json")

  if (!existsSync(keyFile)) {
    console.error(
      "\nNo .dev-zone-keys.json found. Run `pnpm db:seed` first — the database\n" +
        "stores only bcrypt hashes and a hash cannot be turned back into a key.\n"
    )
    process.exit(1)
  }

  const parsed = JSON.parse(readFileSync(keyFile, "utf8")) as {
    generatedAt: string
    keys: Record<string, string>
  }

  if (allZones || registryMode) {
    const prisma = new PrismaClient()
    try {
      if (allZones) {
        console.log("\n  Generating a header per zone\n")
        await writeAllZones(prisma, parsed.keys)
      }
      if (registryMode) {
        console.log("\n  Generating the runtime zone registry\n")
        await writeRegistry(prisma, parsed.keys)
      }
    } finally {
      await prisma.$disconnect()
    }
    return
  }

  const apiKey = parsed.keys[zoneCode]
  if (!apiKey) {
    console.error(
      `\nNo key for zone "${zoneCode}". Known zones: ${Object.keys(parsed.keys).join(", ")}\n`
    )
    process.exit(1)
  }

  const prisma = new PrismaClient()
  try {
    const zone = await prisma.zone.findUnique({
      where: { code: zoneCode },
      include: { sensors: true },
    })

    if (!zone) {
      console.error(
        `\nZone "${zoneCode}" is in the key file but not in the database. Re-run \`pnpm db:seed\`.\n`
      )
      process.exit(1)
    }

    const has = (type: string): boolean =>
      zone.sensors.some((sensor) => sensor.type === type)

    // A channel the zone has no sensor row for is rejected with 422
    // SENSOR_NOT_CONFIGURED, so these flags are derived rather than guessed.
    const reportFlags: Array<[string, boolean]> = [
      ["REPORT_FIRE", has("FLAME")],
      ["REPORT_GAS", has("GAS")],
      ["REPORT_WATER", has("WATER")],
      ["REPORT_OCCUPANCY", has("OCCUPANCY")],
    ]

    const body = [
      "#pragma once",
      "",
      "// GENERATED by `pnpm firmware:config --write` — do not commit.",
      `// Zone: ${zone.name} · keys generated ${parsed.generatedAt}`,
      "// Regenerate after every `pnpm db:seed`; zone API keys rotate by design.",
      "namespace AppConfig {",
      "",
      `static constexpr char ZONE_CODE[] = "${zone.code}";`,
      `static constexpr char ZONE_UUID[] = "${zone.id}";`,
      `static constexpr char ZONE_API_KEY[] = "${apiKey}";`,
      "",
      "// Derived from the sensors this zone actually has — reporting a channel",
      "// the zone has no sensor row for is a 422 SENSOR_NOT_CONFIGURED.",
      ...reportFlags.map(
        ([name, enabled]) =>
          `static constexpr bool ${name.padEnd(18)} = ${enabled ? "true" : "false"};`
      ),
      "",
      "}  // namespace AppConfig",
      "",
    ].join("\n")

    if (shouldWrite) {
      writeFileSync(SECRETS_HEADER, body, "utf8")
      console.log(`\n  Wrote ${path.relative(process.cwd(), SECRETS_HEADER)}`)

      // diagram.json is deliberately left alone. It is the superset board the
      // Wokwi VS Code extension opens, and it works with every build — a zone
      // that does not report a channel simply never reads that pin. Overwriting
      // it here used to strip the parts the multi-room build needs.
      const source = zoneDiagram(zone.code)
      console.log(`  Zone: ${zone.name} (${zone.code})`)
      if (existsSync(source)) {
        console.log(
          `  Board: zones/${zone.code}/diagram.json — pass it with --diagram-file,`
        )
        console.log(
          `         or just use the superset diagram.json that VS Code opens.`
        )
      }
      console.log(
        `  Reporting: ${reportFlags
          .filter(([, on]) => on)
          .map(([n]) => n.replace("REPORT_", "").toLowerCase())
          .join(", ")}`
      )
      console.log("\n  Gitignored. Re-run after every `pnpm db:seed`.\n")
    } else {
      console.log(
        `\n  firmware/include/zone_secrets.h  (zone: ${zone.name}) — pass --write to generate it`
      )
      console.log(`  Keys generated ${parsed.generatedAt}\n`)
      console.log(body)
    }
  } finally {
    await prisma.$disconnect()
  }
}

await main()
